export const POSTGRES_CONFIG_ROOT = "POSTGRES_CONFIG_ROOT";
export const APPLICATION_ROOT = "APPLICATION_ROOT";
export const REDIS_CONFIG_ROOT = "REDIS_CONFIG_ROOT";
export const REDIS_CLIENT = "REDIS_CLIENT";
export const REDIS_CONFIG_PORT = "REDIS_PORT";
export const REDIS_CONFIG_HOST = "REDIS_HOST";
export const REDIS_CONFIG_POOL_SIZE = "REDIS_POOL_SIZE";
